using System;
using System.IO;
using System.Linq;
using UdonSharp;
using UdonSharpEditor;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using VRC.SDK3.Components;
using Yamadev.YamaStream.Editor;
using Yamadev.YamaStream.UI;

namespace Yamadev.YamaStream.Modules.BilibiliSearch.Editor
{
  // Runs before YamaPlayer's -3000 slot injection. Its normal module contract requires
  // a module to be a descendant of Controller, not a sibling under YamaPlayer.
  public class BilibiliSearchBindingProcess : IYamaPlayerBuildProcess
  {
    public int callbackOrder => -3100;
    public void Process()
    {
      foreach (var module in UnityEngine.Object.FindObjectsByType<BilibiliSearch>(FindObjectsInactive.Include, FindObjectsSortMode.None))
      {
        if (!module.gameObject.activeInHierarchy) continue;
        var controller = BilibiliSearchRepair.ResolveController(module);
        if (controller == null) throw new InvalidOperationException("BilibiliSearch: assign Target Controller, or place the module under the intended YamaPlayer Controller.");
        module.BindController(controller);
        if (!module.transform.IsChildOf(controller.transform)) module.transform.SetParent(controller.transform, true);
      }
    }
  }

  /// <summary>
  /// Removes the pointer down handlers an earlier version of this module attached to YamaPlayer's
  /// own url boxes. The module no longer touches them - the panel has its own url page - so the
  /// old handlers would call methods that are gone.
  /// </summary>
  /// <remarks>
  /// Only entries this module added are removed: the target has to be the panel's UdonBehaviour and
  /// the method one of the two the old versions wired.
  /// </remarks>
  public class BilibiliSearchUrlBoxCleanupProcess : IYamaPlayerBuildProcess
  {
    public int callbackOrder => 1000;
    public void Process() { BilibiliSearchRepair.RemoveLegacyUrlBoxWiring(); }
  }

  public static class BilibiliSearchRepair
  {
    /// <summary>Methods older versions of this module wired to YamaPlayer's url boxes.</summary>
    private static readonly string[] LegacyUrlBoxEvents = { "ResetPlayerUrlInput", "OnPlayerUrlClicked" };

    /// <summary>
    /// Drops the url box handlers of older versions of this module, in the whole scene.
    /// </summary>
    /// <returns>The amount of removed entries.</returns>
    public static int RemoveLegacyUrlBoxWiring()
    {
      var uiControllers = UnityEngine.Object.FindObjectsByType<UIController>(FindObjectsInactive.Include, FindObjectsSortMode.None);
      int removed = 0;

      foreach (var uiController in uiControllers)
      {
        foreach (var field in uiController.GetComponentsInChildren<VRCUrlInputField>(true))
        {
          var trigger = field.GetComponent<EventTrigger>();
          if (trigger == null) continue;

          for (int i = trigger.triggers.Count - 1; i >= 0; i--)
          {
            var entry = trigger.triggers[i];
            if (entry == null) continue;

            bool ours = false;
            int calls = entry.callback.GetPersistentEventCount();
            for (int c = 0; c < calls && !ours; c++)
            {
              string method = entry.callback.GetPersistentMethodName(c);
              for (int m = 0; m < LegacyUrlBoxEvents.Length; m++)
              {
                if (method == LegacyUrlBoxEvents[m]) { ours = true; break; }
              }
            }
            if (!ours) continue;

            trigger.triggers.RemoveAt(i);
            removed++;
          }

          if (trigger.triggers.Count == 0) UnityEngine.Object.DestroyImmediate(trigger, true);
        }
      }

      if (removed > 0) Debug.Log($"[BilibiliSearch] Removed {removed} url box handler(s) left over from an older version of the module.");
      return removed;
    }
    /// <summary>
    /// The module prefab ships inside the module folder; assets generated by an older version
    /// of the setup tool may still sit in Assets/Yamadev/YamaPlayerGenerated.
    /// </summary>
    public static GameObject FindModulePrefab()
    {
      string[] paths =
      {
        "Packages/net.kwxxw.yama-stream/Modules/BilibiliSearch/BilibiliSearch.prefab",
        "Assets/Yamadev/YamaPlayerGenerated/BilibiliSearch.prefab",
      };
      for (int i = 0; i < paths.Length; i++)
      {
        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(paths[i]);
        if (prefab != null) return prefab;
      }
      return null;
    }

    public static Controller ResolveController(BilibiliSearch module)
    {
      if (module.Controller != null) return module.Controller;
      var parent = module.GetComponentInParent<Controller>(true);
      if (parent != null) return parent;
      var player = module.GetComponentInParent<YamaPlayer>(true);
      if (player != null) return player.GetComponentInChildren<Controller>(true);
      var controllers = UnityEngine.Object.FindObjectsByType<Controller>(FindObjectsInactive.Include, FindObjectsSortMode.None)
        .Where(c => c.gameObject.scene == module.gameObject.scene).ToArray();
      return controllers.Length == 1 ? controllers[0] : null;
    }

    /// <summary>
    /// Takes every Bilibili Search module instance out of the open scene again.
    /// </summary>
    /// <remarks>
    /// This is the first half of uninstalling: a scene that still holds a prefab instance of the
    /// module would lose it (missing prefab) as soon as the module folder is deleted, so the
    /// instances have to go first. The module's panel is a child of that instance, it is removed
    /// with it; the UI slots of the module are only injected while the world is built, so there is
    /// nothing left in the scene afterwards. The two core fixes of YamaPlayer stay untouched - they
    /// are bug fixes of their own and do not depend on this module.
    /// </remarks>
    [MenuItem("Tools/YamaPlayer/Bilibili Search/Uninstall from Scene", priority = 102)]
    public static void UninstallFromScene()
    {
      if (EditorApplication.isPlayingOrWillChangePlaymode) throw new InvalidOperationException("Exit Play Mode before uninstalling.");

      var modules = UnityEngine.Object.FindObjectsByType<BilibiliSearch>(FindObjectsInactive.Include, FindObjectsSortMode.None);
      int removed = 0;
      for (int i = 0; i < modules.Length; i++)
      {
        var module = modules[i];
        if (module == null || module.gameObject.hideFlags != HideFlags.None || !module.gameObject.scene.IsValid()) continue;
        Undo.DestroyObjectImmediate(module.gameObject);
        removed++;
      }

      // Older versions of the module wired click handlers into YamaPlayer's own url boxes.
      int unwired = RemoveLegacyUrlBoxWiring();

      if (removed > 0) EditorSceneManager.MarkAllScenesDirty();
      Debug.Log($"[BilibiliSearch] Removed {removed} module instance(s) from the open scene, {unwired} leftover url box handler(s). " +
                "Save the scene, then delete Modules/BilibiliSearch to finish uninstalling.");

      if (Application.isBatchMode) return;
      EditorUtility.DisplayDialog(
        "Bilibili Search - uninstall",
        $"Removed {removed} module instance(s) from the open scene (and {unwired} leftover url box handler(s)).\n\n" +
        "Next steps:\n" +
        "1. Save the scene (it was marked dirty).\n" +
        "2. Delete the folder Modules/BilibiliSearch.\n" +
        "3. The two YamaPlayer core fixes can stay: they are bug fixes of their own.\n" +
        "4. A world that was already uploaded keeps the module until it is uploaded again.",
        "OK");
    }

    [MenuItem("Tools/YamaPlayer/Repair Bilibili Search Scene")]
    public static void RepairScene()
    {
      if (EditorApplication.isPlayingOrWillChangePlaymode) throw new InvalidOperationException("Exit Play Mode before repairing the scene.");
      if (!BilibiliSearchPanelSetup.BackendConfigured)
        throw new InvalidOperationException("No backend configured. Run Tools/YamaPlayer/Bilibili Search Setup and enter your own bilibili player address first (see Modules/BilibiliSearch/INSTALL.md).");
      RemoveLegacyUrlBoxWiring();
      foreach (var existing in UnityEngine.Object.FindObjectsByType<BilibiliSearch>(FindObjectsInactive.Include, FindObjectsSortMode.None))
      {
        if (PrefabUtility.IsAnyPrefabInstanceRoot(existing.gameObject))
          PrefabUtility.UnpackPrefabInstance(existing.gameObject, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
      }
      BilibiliSearchPanelSetup.GenerateFromMenu();
      var prefab = FindModulePrefab();
      if (prefab == null) throw new InvalidOperationException("Cannot find the generated BilibiliSearch prefab. Run Tools/YamaPlayer/Bilibili Search Setup first.");
      var modules = UnityEngine.Object.FindObjectsByType<BilibiliSearch>(FindObjectsInactive.Include, FindObjectsSortMode.None);
      int repaired = 0;
      foreach (var old in modules)
      {
        if (old == null || old.gameObject.hideFlags != HideFlags.None || !old.gameObject.scene.IsValid()) continue;
        var controller = ResolveController(old);
        if (controller == null) throw new InvalidOperationException("Cannot uniquely resolve player for " + old.name + ". Assign Target Controller first.");
        var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab, controller.transform);
        instance.name = old.name;
        instance.transform.position = old.transform.position;
        instance.transform.rotation = old.transform.rotation;
        instance.SetActive(old.gameObject.activeSelf);
        Undo.RegisterCreatedObjectUndo(instance, "Repair Bilibili Search");
        var replacement = instance.GetComponent<BilibiliSearch>();
        replacement.BindController(controller);
        if (old.Service != null)
        {
          // Only the tuning value is carried over. The backend url is deliberately NOT: it comes
          // from the setup window, and the instance was just built from the prefab that the tool
          // regenerated with it, so copying the old value would silently keep a stale server
          // address alive after the address was changed.
          var source = new SerializedObject(old.Service);
          var dest = new SerializedObject(replacement.Service);
          dest.FindProperty("_maxResults").intValue = source.FindProperty("_maxResults").intValue;
          dest.ApplyModifiedPropertiesWithoutUndo();
        }
        foreach (var proxy in instance.GetComponentsInChildren<UdonSharpBehaviour>(true))
        {
          UdonSharpEditorUtility.CopyProxyToUdon(proxy);
          PrefabUtility.RecordPrefabInstancePropertyModifications(proxy);
        }
        Undo.DestroyObjectImmediate(old.gameObject);
        EditorSceneManager.MarkSceneDirty(instance.scene);
        repaired++;
      }
      ValidateGenerated();
      EditorSceneManager.SaveOpenScenes();
      Debug.Log("BILIBILI_REPAIR_OK: " + repaired + " scene modules repaired and saved.");
    }

    [MenuItem("Tools/YamaPlayer/Validate Bilibili Search")]
    public static void ValidateGenerated()
    {
      string[] paths = { "Assets/Yamadev/YamaPlayerGenerated/BilibiliSearchPanel.prefab", "Assets/Yamadev/YamaPlayerGenerated/BilibiliSearch.prefab" };
      int checkedCount = 0;
      foreach (var path in paths)
      {
        var root = PrefabUtility.LoadPrefabContents(path);
        try
        {
          foreach (var t in root.GetComponentsInChildren<Transform>(true))
          {
            if (GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(t.gameObject) != 0) throw new Exception("Missing script: " + t.name);
          }
          foreach (var proxy in root.GetComponentsInChildren<UdonSharpBehaviour>(true))
          {
            var backing = UdonSharpEditorUtility.GetBackingUdonBehaviour(proxy);
            if (backing == null || backing.programSource == null || backing.gameObject != proxy.gameObject || !backing.transform.IsChildOf(root.transform)) throw new Exception("Invalid backing behaviour: " + proxy.name);
            var data = new SerializedObject(proxy);
            var it = data.GetIterator();
            while (it.Next(true))
            {
              if (it.propertyType != SerializedPropertyType.ObjectReference) continue;
              var c = it.objectReferenceValue as Component;
              var go = it.objectReferenceValue as GameObject;
              var tr = c != null ? c.transform : go != null ? go.transform : null;
              if (tr != null && !tr.IsChildOf(root.transform)) throw new Exception("Cross-prefab scene reference: " + proxy.name + "." + it.propertyPath);
            }
            checkedCount++;
          }
          foreach (var button in root.GetComponentsInChildren<UnityEngine.UI.Button>(true))
          {
            if (button.onClick.GetPersistentEventCount() != 1) throw new Exception("Missing persistent button event: " + button.name);
            var target = button.onClick.GetPersistentTarget(0) as VRC.Udon.UdonBehaviour;
            if (target == null || !target.transform.IsChildOf(root.transform)) throw new Exception("Wrong button target: " + button.name);
            checkedCount++;
          }
          var definition = root.GetComponent<YamaPlayerModuleDefinition>();
          if (definition != null)
          {
            if (definition.uiSlots[0].content == null || !definition.uiSlots[0].content.transform.IsChildOf(root.transform)) throw new Exception("Slot must reference an internal panel object.");
            var module = root.GetComponent<BilibiliSearch>();
            if (module.Service == null || module.Result == null || module.UIBehaviour == null) throw new Exception("Incomplete module.");
            if ((BilibiliSearch)new SerializedObject(module.UIBehaviour).FindProperty("_search").objectReferenceValue != module) throw new Exception("Panel target not wired.");
          }
        }
        finally { PrefabUtility.UnloadPrefabContents(root); }
      }
      // The parser must not care about the host: every world points the module at its own backend.
      const string prefix = "https://bili.example.com/player/?";
      if (BiliUrlUtility.Page(prefix + "page=12&keyword=test") != 12 ||
          BiliUrlUtility.Page(prefix + "keyword=test&page=12") != 12 ||
          BiliUrlUtility.Keyword(prefix + "keyword=%E6%B5%8B%E8%AF%95&page=2") != "测试" ||
          BiliUrlUtility.ChangePage(prefix + "keyword=a%26b&page=1", 2) != prefix + "keyword=a%26b&page=2" ||
          BiliUrlUtility.ChangePage(prefix + "page=1&keyword=a%26b", 2) != prefix + "page=2&keyword=a%26b" ||
          BiliUrlUtility.Page(prefix + "page=0&keyword=test") != 0 ||
          BiliUrlUtility.Page("https://other.example.com/player/?page=1&keyword=test") != 1 ||
          BiliUrlUtility.Page("https://bili.example.com/player/?page=1&keyword=") != 0 ||
          BiliUrlUtility.Page("https://bili.example.com/player/") != 0 ||
          BiliUrlUtility.IsBv("BV../invalid")) throw new Exception("URL regression test failed.");
      string dir = Path.Combine(Path.GetDirectoryName(Application.dataPath), "work");
      Directory.CreateDirectory(dir);
      File.WriteAllText(Path.Combine(dir, "BilibiliSearch-validation.txt"), "PASS: " + checkedCount + " prefab behaviour/event checks; URL parsing regression checks.\n");
      Debug.Log("BILIBILI_VALIDATION_OK " + checkedCount);
    }
  }
}
